/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PuppyIdRouteImport } from './routes/puppy.$id'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as ApiPublicEnsureAdminRouteImport } from './routes/api/public/ensure-admin'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PuppyIdRoute = PuppyIdRouteImport.update({
  id: '/puppy/$id',
  path: '/puppy/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEnsureAdminRoute = ApiPublicEnsureAdminRouteImport.update({
  id: '/api/public/ensure-admin',
  path: '/api/public/ensure-admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/order/$id': typeof OrderIdRoute
  '/puppy/$id': typeof PuppyIdRoute
  '/api/public/ensure-admin': typeof ApiPublicEnsureAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/order/$id': typeof OrderIdRoute
  '/puppy/$id': typeof PuppyIdRoute
  '/api/public/ensure-admin': typeof ApiPublicEnsureAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/order/$id': typeof OrderIdRoute
  '/puppy/$id': typeof PuppyIdRoute
  '/api/public/ensure-admin': typeof ApiPublicEnsureAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/order/$id'
    | '/puppy/$id'
    | '/api/public/ensure-admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/order/$id'
    | '/puppy/$id'
    | '/api/public/ensure-admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/order/$id'
    | '/puppy/$id'
    | '/api/public/ensure-admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  OrderIdRoute: typeof OrderIdRoute
  PuppyIdRoute: typeof PuppyIdRoute
  ApiPublicEnsureAdminRoute: typeof ApiPublicEnsureAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puppy/$id': {
      id: '/puppy/$id'
      path: '/puppy/$id'
      fullPath: '/puppy/$id'
      preLoaderRoute: typeof PuppyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ensure-admin': {
      id: '/api/public/ensure-admin'
      path: '/api/public/ensure-admin'
      fullPath: '/api/public/ensure-admin'
      preLoaderRoute: typeof ApiPublicEnsureAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  OrderIdRoute: OrderIdRoute,
  PuppyIdRoute: PuppyIdRoute,
  ApiPublicEnsureAdminRoute: ApiPublicEnsureAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
